server:
  port: 16002
spring:
  application:
    name: stream-sink
management:
  security:
    enabled: false
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: source-channel
        input:
          destination: sink-channel