server:
  port: 16001
fixedDelay: 5000
spring:
  application:
    name: stream-source
  cloud:
    stream:
      bindings:
        output:
          destination: source-channel
management:
  security:
    enabled: false