server:
  port: 13000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
management:
  security:
    enabled: false
spring:
  application:
    name: zuul-gateway
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:15000
zuul:
  ignored-services: "*"
  routes:
    ProductService:
      path: /p/**
      stripPrefix: false ##必须加上，不然路由不到
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true
    serviceUrl:
       defaultZone: http://127.0.0.1:10000/eureka/